# mosquitto_local.conf
# Configuración local simplificada
# Proyecto Seguridad de Tráfico - ARQUI2B_2S2025_GL4

listener 1883
allow_anonymous true
persistence false
log_type all
log_dest stdout

# No vuelvas a abrir otro listener o puerto adicional